### ISSUE TITLE
参考你的代码，采用的svg图标在火狐浏览器动态替换失败

### ISSUE THREAD

**Issue by denghp** [no-simple/vue-tree-table#1]
### 火狐浏览器：
![image](https://user-images.githubusercontent.com/2291149/49706235-abd8b980-fc5f-11e8-9bbb-df153e1bea7a.png)

![image](https://user-images.githubusercontent.com/2291149/49706138-ceb69e00-fc5e-11e8-8e52-d1ca43e1eff2.png)

![image](https://user-images.githubusercontent.com/2291149/49706165-14736680-fc5f-11e8-8733-652246804b76.png)

### chrome浏览器：
![image](https://user-images.githubusercontent.com/2291149/49706225-9a8fad00-fc5f-11e8-8d37-3ea82b5da970.png)

#### 分析：
1、svg 节点下的use xlink:href引用的值变了，但是symbol id值没有变化
2、正常情况下symbol id值应该也发生变化，如图三
3、chrome,safari 没有问题

#### 问题：
不知道你遇到类似情况没，有没有好的解决方案？

**Comment by no-simple** [comment]
才看到该issue,请问还有问题吗？

**Comment by denghp** [comment]
暂时只遇到这个问题，别的没有发现

**Comment by no-simple** [comment]
可以考虑直接换成图片
